pages:
  stage: deploy
  script:
    # Copiar todo excepto la carpeta public usando shell nativo
    - find . -mindepth 1 -maxdepth 1 ! -name 'public' -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - main
